# Generated by Django 4.0.6 on 2022-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0002_comics_manga_novela_delete_autor_delete_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comics',
            name='genero',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='manga',
            name='genero',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='novela',
            name='genero',
            field=models.CharField(max_length=150),
        ),
    ]
