# Generated by Django 4.0.6 on 2022-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0005_rename_user_avatar_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comics',
            name='imagen_libro',
            field=models.ImageField(null=True, upload_to='imagenes_libros'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
