# Generated by Django 4.0.6 on 2022-08-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0007_manga_imagen_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='novela',
            name='imagen_libro',
            field=models.ImageField(null=True, upload_to='imagenes_libros'),
        ),
    ]
